version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./database:/var/www/database
        ports:
            - "9000:9000"
        networks:
            - core-net

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        command: sh -c "php artisan queue:work --queue events --sleep 5 --tries 2"
        restart: on-failure
        depends_on:
            - app
            - redis

    mysql:
        image: mysql:latest
        container_name: poolticket_mysql
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: 'poolticket_exam_db'
            MYSQL_USER: 'poolticket_admin'
            MYSQL_PASSWORD: '1234'
            MYSQL_ROOT_PASSWORD: '1234'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - mysql-db:/var/lib/mysql
        networks:
            - core-net

    nginx:
        image: nginx:stable-alpine
        container_name: poolticket_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - core-net

    redis:
        image: redis:alpine
        container_name: poolticket_redis
        ports:
            - "6379:6379"
        networks:
            - core-net

volumes:
    mysql-db:

networks:
    core-net:
        driver: bridge
